"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DhM4jtsvelT
 */
import {
  SelectValue,
  SelectTrigger,
  SelectLabel,
  SelectItem,
  SelectGroup,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useChat } from "ai/react";

export function Chatbot() {
  const { messages, isLoading, input, handleInputChange, handleSubmit } =
    useChat({
      initialMessages: [
        {
          id: "1",
          role: "system",
          content: "eres un chatbot que responde con acento paisa",
        },
        {
          id: "2",
          role: "assistant",
          content:
            "¡Hola! 🌟 Soy tu asistente virtual aquí para ayudarte. ¿En qué puedo asistirte hoy?",
        },
      ],
    });

  return (
    <section className="w-full h-screen bg-gray-50 flex flex-col">
      <header className="flex justify-between items-center p-4 bg-white shadow-md border-b border-gray-300">
        <div className="flex items-center space-x-2">
          <img
            alt="Logo"
            className="rounded-full"
            height="32"
            src="/placeholder.svg"
            style={{
              aspectRatio: "32/32",
              objectFit: "cover",
            }}
            width="32"
          />
          <h1 className="text-lg text-black font-bold">Company Name</h1>
        </div>
        <div className="flex items-center space-x-4">
          <div className="relative w-64">
            <Select className="w-full bg-white rounded-md text-gray-900">
              <SelectTrigger className="flex items-center space-x-1 text-gray-900">
                <svg
                  className=" h-5 w-5"
                  fill="none"
                  height="24"
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                  width="24"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <circle cx="12" cy="12" r="10" />
                  <line x1="2" x2="22" y1="12" y2="12" />
                  <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
                </svg>
                <SelectValue placeholder="Language" />
              </SelectTrigger>
              <SelectContent className="rounded-md shadow-lg bg-white w-full">
                <SelectGroup>
                  <SelectLabel className="text-gray-900">Languages</SelectLabel>
                  <SelectItem value="english">English</SelectItem>
                  <SelectItem value="spanish">Spanish</SelectItem>
                  <SelectItem value="french">French</SelectItem>
                  <SelectItem value="german">German</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
        </div>
      </header>
      <div className="flex-grow overflow-auto p-4 space-y-4 flex flex-col bg-gray-100">
        {messages
          .filter((message) => message.role !== "system")
          .map((message, i, row) => (
            <div
              className={`p-4 rounded-lg shadow ${
                message.role === "assistant"
                  ? "bg-blue-100 self-start"
                  : "bg-green-100 self-end"
              }`}
              key={message.id}
            >
              <p className="text-gray-900">{message.content}</p>
            </div>
          ))}
      </div>
      <div className="border-t border-gray-300 p-4 bg-white">
        <form className="flex space-x-2 items-center" onSubmit={handleSubmit}>
          <Textarea
            className="flex-grow rounded-md bg-white text-gray-900"
            placeholder="Type your message here..."
            value={input}
            onChange={handleInputChange}
          />
          <Button
            className="w-20 bg-black text-white"
            type="submit"
            disabled={isLoading}
          >
            {isLoading ? (
              <svg
                className=" animate-spin h-5 w-5 text-white-900"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <line x1="12" x2="12" y1="2" y2="6" />
                <line x1="12" x2="12" y1="18" y2="22" />
                <line x1="4.93" x2="7.76" y1="4.93" y2="7.76" />
                <line x1="16.24" x2="19.07" y1="16.24" y2="19.07" />
                <line x1="2" x2="6" y1="12" y2="12" />
                <line x1="18" x2="22" y1="12" y2="12" />
                <line x1="4.93" x2="7.76" y1="19.07" y2="16.24" />
                <line x1="16.24" x2="19.07" y1="7.76" y2="4.93" />
              </svg>
            ) : (
              "Send"
            )}
          </Button>
        </form>
      </div>
    </section>
  );
}
