"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ra80o9UCqIh
 */
import {
  SelectValue,
  SelectTrigger,
  SelectLabel,
  SelectItem,
  SelectGroup,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useRef, useState } from "react";
import { getAnswer } from "@/lib/api";

export function Chatbot() {
  const [messages, setMessages] = useState([
    {
      message: "Hello! How can I assist you today?",
      timestamp: "Nov 8, 2023, 10:00 AM",
      role: "assistant",
    },
  ]);

  const textAreaRef = useRef(null);

  async function handleNewMessage() {
    const message = textAreaRef.current.value;
    setMessages((prevArray) => [
      ...prevArray,
      { message, timestamp: new Date().toString(), role: "user" },
    ]);

    textAreaRef.current.value = "";

    const response = await getAnswer(message);
    setMessages((prevArray) => [
      ...prevArray,
      {
        message: response,
        timestamp: new Date().toString(),
        role: "assistant",
      },
    ]);
  }

  return (
    <section className="w-full h-screen bg-gray-100 dark:bg-gray-900 flex flex-col">
      <div className="flex-grow overflow-auto p-4 space-y-4">
        {messages.map((message, index) => (
          <div
            className={`p-4 rounded-lg ${
              message.role === "assistant"
                ? "bg-white dark:bg-gray-800"
                : "bg-blue-200 dark:bg-blue-700"
            } shadow ml-auto`}
            key={index}
          >
            <p className="text-black dark:text-white">{message.message}</p>
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
              {message.timestamp}
            </p>
          </div>
        ))}
      </div>
      <div className="border-t border-gray-200 dark:border-gray-700 p-4">
        <div className="flex items-center space-x-2">
          <Select className="mr-2 w-32">
            <SelectTrigger>
              <SelectValue placeholder="Select language" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectLabel>Languages</SelectLabel>
                <div className="flex items-center">
                  <svg
                    className=" h-5 w-5 mr-1"
                    fill="none"
                    height="24"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    width="24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
                    <line x1="4" x2="4" y1="22" y2="15" />
                  </svg>
                  <SelectItem value="english">English</SelectItem>
                </div>
                <div className="flex items-center">
                  <svg
                    className=" h-5 w-5 mr-1"
                    fill="none"
                    height="24"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    width="24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
                    <line x1="4" x2="4" y1="22" y2="15" />
                  </svg>
                  <SelectItem value="spanish">Spanish</SelectItem>
                </div>
                <div className="flex items-center">
                  <svg
                    className=" h-5 w-5 mr-1"
                    fill="none"
                    height="24"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    width="24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
                    <line x1="4" x2="4" y1="22" y2="15" />
                  </svg>
                  <SelectItem value="french">French</SelectItem>
                </div>
                <div className="flex items-center">
                  <svg
                    className=" h-5 w-5 mr-1"
                    fill="none"
                    height="24"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    width="24"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
                    <line x1="4" x2="4" y1="22" y2="15" />
                  </svg>
                  <SelectItem value="german">German</SelectItem>
                </div>
              </SelectGroup>
            </SelectContent>
          </Select>
          <Textarea
            className="flex-grow rounded-md"
            placeholder="Type your message here..."
            ref={textAreaRef}
          />
          <Button onClick={handleNewMessage}>Send</Button>
        </div>
      </div>
    </section>
  );
}
